sudo: false
language: go
go:
  - 1.7
  - 1.8
  - 1.9
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=slss.coverprofile
  - goveralls -coverprofile=slss.coverprofile -service=travis-ci
